import { Geist, Geist_Mono, Oswald, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./shared/Navbar";
import Footer from "./shared/Footer";
import ExerciseProvider from "./context/ExerciseContext";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FitLog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body
        className={`${inter.className} flex min-h-screen flex-col bg-[#0c0d10]`}
      >
        <ExerciseProvider>

          <Navbar />

          <main className="flex-1">
            {children}
          </main>

          <Footer />
          <ToastContainer
            autoClose={2000}
            hideProgressBar
            theme="dark"
            closeButton={false}
            toastStyle={{
              width: "fit-content",
              minHeight: "auto",
              backgroundColor: "#15171d",
              fontSize: "0.875rem",
              marginRight: "2rem",
            }}
          />
        </ExerciseProvider>

      </body>
    </html>
  );
}